A branch named nichita_orlic has been created
eugene-okulik/Lerei pull request #1
Opened 2024-05-29 16:31 UTC by md3500

2024-05-29 18:26 UTC, md3500 commented
@eugene-okulik please, review

2024-05-30 10:08 UTC, eugene-okulik requested changes
Как написано в задании, первый вариант не принимаю и указываю, что нужны изменения. Это просто для того, чтобы нам попрактиковаться в том, как мы будем взаимодействовать.  
Добавь в файл какую-нибудь букву, коммитай и запушивай.

2024-05-30 11:59 UTC, md3500 commented
@eugene-okulik please, review

2024-05-30 12:07 UTC, eugene-okulik approved these changes

2024-05-30 12:33 UTC, merged